[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ARG002",   # unused-method-argument: Necessary in inherited methods
    "COM812",   # missing-trailing-comma: Incompatible with ruff format
    "D413",     # missing-blank-line-after-last-section: Style preference
    "N812",     # lowercase-imported-as-non-lowercase: To follow torch conventions
    "PLR2004",  # magic-value-comparison: Excessive constraint
    "RET504",   # unnecessary-assign: Makes code more readable
    "S101",     # assert: Asserts are OK for unit tests and function checks
    "S603",     # subprocess-without-shell-equal-true: Excessive constraint
    "T201",     # print: Print statements are OK for debugging and in tests
]
